# Generated by Django 5.0.6 on 2024-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.IntegerField(unique=True)),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Grade', models.CharField(blank=True, max_length=10, null=True)),
                ('Photo', models.URLField(blank=True, null=True)),
                ('Schedule', models.URLField(blank=True, null=True)),
                ('Social_Media', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Contact_1', models.CharField(blank=True, max_length=12, null=True)),
                ('Contact_2', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
