# Generated by Django 4.2.13 on 2024-06-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentBase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="static/media/default-avatar.jpg",
                null=True,
                upload_to="",
            ),
        ),
    ]
