# Generated by Django 5.0.6 on 2024-06-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Photo',
        ),
    ]
