# Generated by Django 5.0.6 on 2024-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentBase', '0002_remove_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
