# Generated by Django 5.0.6 on 2024-06-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentBase', '0003_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Schedule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
