# Generated by Django 4.2.13 on 2024-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentBase", "0004_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="Email_status"),
        ),
    ]
