# Generated by Django 5.0.6 on 2024-06-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentBase', '0004_alter_profile_photo_alter_profile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
