# Generated by Django 4.2.13 on 2024-06-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentBase", "0005_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
