# Generated by Django 4.2.13 on 2024-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentBase", "0006_user_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="student_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
