# Generated by Django 4.2.13 on 2024-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentBase", "0010_alter_message_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="subject",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
